// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using staGledas.Service.Database;

#nullable disable

namespace staGledas.Service.Migrations
{
    [DbContext(typeof(StaGledasContext))]
    [Migration("20260109220547_ChangeOcjenaToDouble")]
    partial class ChangeOcjenaToDouble
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("staGledas.Service.Database.Favoriti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumDodavanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("KorisnikId", "FilmId")
                        .IsUnique();

                    b.ToTable("Favoriti");
                });

            modelBuilder.Entity("staGledas.Service.Database.Filmovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrojLajkova")
                        .HasColumnType("int");

                    b.Property<int?>("BrojOcjena")
                        .HasColumnType("int");

                    b.Property<int?>("BrojPregleda")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GodinaIzdanja")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ProsjecnaOcjena")
                        .HasColumnType("float");

                    b.Property<string>("Reziser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("int");

                    b.Property<int?>("Trajanje")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Filmovi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrojOcjena = 100,
                            BrojPregleda = 500,
                            DatumIzmjene = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumKreiranja = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GodinaIzdanja = 2010,
                            Naslov = "Inception",
                            Opis = "A thief who steals corporate secrets through dream-sharing technology.",
                            ProsjecnaOcjena = 4.5,
                            Reziser = "Christopher Nolan",
                            Trajanje = 148
                        },
                        new
                        {
                            Id = 2,
                            BrojOcjena = 80,
                            BrojPregleda = 400,
                            DatumIzmjene = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumKreiranja = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GodinaIzdanja = 2013,
                            Naslov = "The Wolf of Wall Street",
                            Opis = "Based on the true story of Jordan Belfort.",
                            ProsjecnaOcjena = 4.2000000000000002,
                            Reziser = "Martin Scorsese",
                            Trajanje = 180
                        },
                        new
                        {
                            Id = 3,
                            BrojOcjena = 60,
                            BrojPregleda = 300,
                            DatumIzmjene = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumKreiranja = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GodinaIzdanja = 2019,
                            Naslov = "Once Upon a Time in Hollywood",
                            Opis = "A faded television actor and his stunt double strive to achieve fame.",
                            ProsjecnaOcjena = 4.0,
                            Reziser = "Quentin Tarantino",
                            Trajanje = 161
                        });
                });

            modelBuilder.Entity("staGledas.Service.Database.FilmoviGlumci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("GlumacId")
                        .HasColumnType("int");

                    b.Property<string>("Uloga")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("GlumacId");

                    b.ToTable("FilmoviGlumci");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FilmId = 1,
                            GlumacId = 1,
                            Uloga = "Dom Cobb"
                        },
                        new
                        {
                            Id = 2,
                            FilmId = 2,
                            GlumacId = 1,
                            Uloga = "Jordan Belfort"
                        },
                        new
                        {
                            Id = 3,
                            FilmId = 2,
                            GlumacId = 3,
                            Uloga = "Naomi Lapaglia"
                        },
                        new
                        {
                            Id = 4,
                            FilmId = 3,
                            GlumacId = 1,
                            Uloga = "Rick Dalton"
                        },
                        new
                        {
                            Id = 5,
                            FilmId = 3,
                            GlumacId = 2,
                            Uloga = "Cliff Booth"
                        },
                        new
                        {
                            Id = 6,
                            FilmId = 3,
                            GlumacId = 3,
                            Uloga = "Sharon Tate"
                        });
                });

            modelBuilder.Entity("staGledas.Service.Database.FilmoviLajkovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumLajka")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("KorisnikId", "FilmId")
                        .IsUnique();

                    b.ToTable("FilmoviLajkovi");
                });

            modelBuilder.Entity("staGledas.Service.Database.FilmoviZanrovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("ZanrId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("ZanrId");

                    b.ToTable("FilmoviZanrovi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FilmId = 1,
                            ZanrId = 1
                        },
                        new
                        {
                            Id = 2,
                            FilmId = 1,
                            ZanrId = 5
                        },
                        new
                        {
                            Id = 3,
                            FilmId = 1,
                            ZanrId = 6
                        },
                        new
                        {
                            Id = 4,
                            FilmId = 2,
                            ZanrId = 2
                        },
                        new
                        {
                            Id = 5,
                            FilmId = 2,
                            ZanrId = 3
                        },
                        new
                        {
                            Id = 6,
                            FilmId = 3,
                            ZanrId = 2
                        },
                        new
                        {
                            Id = 7,
                            FilmId = 3,
                            ZanrId = 3
                        });
                });

            modelBuilder.Entity("staGledas.Service.Database.Glumci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biografija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlikaPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Glumci");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biografija = "Americki glumac",
                            DatumRodjenja = new DateTime(1974, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ime = "Leonardo",
                            Prezime = "DiCaprio"
                        },
                        new
                        {
                            Id = 2,
                            Biografija = "Americki glumac i producent",
                            DatumRodjenja = new DateTime(1963, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ime = "Brad",
                            Prezime = "Pitt"
                        },
                        new
                        {
                            Id = 3,
                            Biografija = "Australska glumica",
                            DatumRodjenja = new DateTime(1990, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ime = "Margot",
                            Prezime = "Robbie"
                        },
                        new
                        {
                            Id = 4,
                            Biografija = "Americka glumica",
                            DatumRodjenja = new DateTime(1984, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ime = "Scarlett",
                            Prezime = "Johansson"
                        },
                        new
                        {
                            Id = 5,
                            Biografija = "Americki glumac",
                            DatumRodjenja = new DateTime(1965, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Ime = "Robert",
                            Prezime = "Downey Jr."
                        });
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubFilmova", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxClanova")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("VlasnikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VlasnikId");

                    b.ToTable("KlubFilmova");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubFilmovaClanovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPridruzivanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("KlubId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Uloga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlubId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("KlubFilmovaClanovi");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubKomentari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("ObjavaId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentKomentarId")
                        .HasColumnType("int");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ObjavaId");

                    b.HasIndex("ParentKomentarId");

                    b.ToTable("KlubKomentari");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubLajkovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumLajka")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("ObjavaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjavaId");

                    b.HasIndex("KorisnikId", "ObjavaId")
                        .IsUnique();

                    b.ToTable("KlubLajkovi");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubObjave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumBrisanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KlubId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlubId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("KlubObjave");
                });

            modelBuilder.Entity("staGledas.Service.Database.Korisnici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumBrisanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumIzmjene = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumKreiranja = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@stagledas.com",
                            Ime = "Admin",
                            IsDeleted = false,
                            IsPremium = false,
                            KorisnickoIme = "admin",
                            LozinkaHash = "nhTP4pnrmrmSwxy9q6NHLi2OATA=",
                            LozinkaSalt = "DFzSYJIVSCHU2EAlvmbMbg==",
                            Prezime = "Admin",
                            Status = true,
                            Telefon = "061000000"
                        },
                        new
                        {
                            Id = 2,
                            DatumIzmjene = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumKreiranja = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test@stagledas.com",
                            Ime = "Test",
                            IsDeleted = false,
                            IsPremium = true,
                            KorisnickoIme = "test",
                            LozinkaHash = "nhTP4pnrmrmSwxy9q6NHLi2OATA=",
                            LozinkaSalt = "DFzSYJIVSCHU2EAlvmbMbg==",
                            Prezime = "User",
                            Status = true,
                            Telefon = "062000000"
                        });
                });

            modelBuilder.Entity("staGledas.Service.Database.KorisniciUloge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("UlogaId");

                    b.ToTable("KorisniciUloge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KorisnikId = 1,
                            UlogaId = 1
                        },
                        new
                        {
                            Id = 2,
                            KorisnikId = 2,
                            UlogaId = 2
                        },
                        new
                        {
                            Id = 3,
                            KorisnikId = 2,
                            UlogaId = 3
                        });
                });

            modelBuilder.Entity("staGledas.Service.Database.Novosti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int?>("BrojPregleda")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kategorija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naslov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Novosti");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutorId = 1,
                            BrojPregleda = 150,
                            DatumKreiranja = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kategorija = "Oscars",
                            Naslov = "Oscars 2025: Najbolji filmovi godine",
                            Sadrzaj = "Pregled nominacija za Oscara 2025. Saznajte koji filmovi su u utrci za najvaznije filmske nagrade."
                        },
                        new
                        {
                            Id = 2,
                            AutorId = 1,
                            BrojPregleda = 230,
                            DatumKreiranja = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kategorija = "Vijesti",
                            Naslov = "Novi Nolan film najavljljen za 2026",
                            Sadrzaj = "Christopher Nolan najavio je svoj novi projekt koji ce biti objavljen 2026. godine."
                        });
                });

            modelBuilder.Entity("staGledas.Service.Database.Poruke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumCitanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumSlanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("PosiljateljId")
                        .HasColumnType("int");

                    b.Property<int>("PrimateljId")
                        .HasColumnType("int");

                    b.Property<bool>("Procitano")
                        .HasColumnType("bit");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PosiljateljId");

                    b.HasIndex("PrimateljId");

                    b.ToTable("Poruke");
                });

            modelBuilder.Entity("staGledas.Service.Database.Pratitelji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPracenja")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("PratiteljId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("PratiteljId");

                    b.ToTable("Pratitelji");
                });

            modelBuilder.Entity("staGledas.Service.Database.Pretplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumIsteka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumPocetka")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePriceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Pretplate");
                });

            modelBuilder.Entity("staGledas.Service.Database.Recenzije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumSkrivanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<bool>("ImaSpoiler")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ocjena")
                        .HasColumnType("float");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Recenzije");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumKreiranja = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 1,
                            ImaSpoiler = false,
                            IsHidden = false,
                            KorisnikId = 2,
                            Naslov = "Remek djelo!",
                            Ocjena = 5.0,
                            Sadrzaj = "Inception je jedan od najboljih filmova koje sam ikada gledao. Nolan je genij."
                        },
                        new
                        {
                            Id = 2,
                            DatumKreiranja = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 2,
                            ImaSpoiler = false,
                            IsHidden = false,
                            KorisnikId = 2,
                            Naslov = "Odlicna gluma",
                            Ocjena = 4.0,
                            Sadrzaj = "DiCaprio je bio nevjerovatan u ulozi Jordan Belforta."
                        });
                });

            modelBuilder.Entity("staGledas.Service.Database.Uloge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uloge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Administrator",
                            Opis = "Administrator sistema"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Korisnik",
                            Opis = "Standardni korisnik"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "PremiumKorisnik",
                            Opis = "Premium korisnik sa dodatnim privilegijama"
                        });
                });

            modelBuilder.Entity("staGledas.Service.Database.Watchlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumDodavanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumGledanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<bool?>("Pogledano")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Watchlist");
                });

            modelBuilder.Entity("staGledas.Service.Database.Zalbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumObrade")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("ObradioPrijavuId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Razlog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecenzijaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ObradioPrijavuId");

                    b.HasIndex("RecenzijaId");

                    b.ToTable("Zalbe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumKreiranja = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KorisnikId = 1,
                            Opis = "Recenzija sadrži uvredljive komentare.",
                            Razlog = "Neprimjeren sadržaj",
                            RecenzijaId = 1,
                            Status = "pending"
                        },
                        new
                        {
                            Id = 2,
                            DatumKreiranja = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KorisnikId = 1,
                            Opis = "Korisnik je otkrio ključne dijelove radnje bez spoiler upozorenja.",
                            Razlog = "Spoiler bez upozorenja",
                            RecenzijaId = 2,
                            Status = "pending"
                        },
                        new
                        {
                            Id = 3,
                            DatumKreiranja = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumObrade = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KorisnikId = 2,
                            ObradioPrijavuId = 1,
                            Opis = "Recenzija sadrži netočne informacije o filmu.",
                            Razlog = "Lažne informacije",
                            RecenzijaId = 1,
                            Status = "approved"
                        },
                        new
                        {
                            Id = 4,
                            DatumKreiranja = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumObrade = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KorisnikId = 2,
                            ObradioPrijavuId = 1,
                            Opis = "Recenzija je očigledno promotivni sadržaj.",
                            Razlog = "Spam",
                            RecenzijaId = 2,
                            Status = "rejected"
                        });
                });

            modelBuilder.Entity("staGledas.Service.Database.Zanrovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zanrovi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Akcija",
                            Opis = "Akcioni filmovi"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Komedija",
                            Opis = "Komicni filmovi"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "Drama",
                            Opis = "Dramski filmovi"
                        },
                        new
                        {
                            Id = 4,
                            Naziv = "Horor",
                            Opis = "Horor filmovi"
                        },
                        new
                        {
                            Id = 5,
                            Naziv = "Sci-Fi",
                            Opis = "Naucna fantastika"
                        },
                        new
                        {
                            Id = 6,
                            Naziv = "Triler",
                            Opis = "Triler filmovi"
                        },
                        new
                        {
                            Id = 7,
                            Naziv = "Romantika",
                            Opis = "Romantični filmovi"
                        },
                        new
                        {
                            Id = 8,
                            Naziv = "Animirani",
                            Opis = "Animirani filmovi"
                        });
                });

            modelBuilder.Entity("staGledas.Service.Database.Favoriti", b =>
                {
                    b.HasOne("staGledas.Service.Database.Filmovi", "Film")
                        .WithMany("Favoriti")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany("Favoriti")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("staGledas.Service.Database.FilmoviGlumci", b =>
                {
                    b.HasOne("staGledas.Service.Database.Filmovi", "Film")
                        .WithMany("FilmoviGlumci")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Glumci", "Glumac")
                        .WithMany("FilmoviGlumci")
                        .HasForeignKey("GlumacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Glumac");
                });

            modelBuilder.Entity("staGledas.Service.Database.FilmoviLajkovi", b =>
                {
                    b.HasOne("staGledas.Service.Database.Filmovi", "Film")
                        .WithMany("Lajkovi")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany("FilmoviLajkovi")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("staGledas.Service.Database.FilmoviZanrovi", b =>
                {
                    b.HasOne("staGledas.Service.Database.Filmovi", "Film")
                        .WithMany("FilmoviZanrovi")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Zanrovi", "Zanr")
                        .WithMany("FilmoviZanrovi")
                        .HasForeignKey("ZanrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Zanr");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubFilmova", b =>
                {
                    b.HasOne("staGledas.Service.Database.Korisnici", "Vlasnik")
                        .WithMany()
                        .HasForeignKey("VlasnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vlasnik");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubFilmovaClanovi", b =>
                {
                    b.HasOne("staGledas.Service.Database.KlubFilmova", "Klub")
                        .WithMany("Clanovi")
                        .HasForeignKey("KlubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klub");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubKomentari", b =>
                {
                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany("KlubKomentari")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.KlubObjave", "Objava")
                        .WithMany("Komentari")
                        .HasForeignKey("ObjavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.KlubKomentari", "ParentKomentar")
                        .WithMany()
                        .HasForeignKey("ParentKomentarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Korisnik");

                    b.Navigation("Objava");

                    b.Navigation("ParentKomentar");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubLajkovi", b =>
                {
                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany("KlubLajkovi")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.KlubObjave", "Objava")
                        .WithMany("Lajkovi")
                        .HasForeignKey("ObjavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Objava");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubObjave", b =>
                {
                    b.HasOne("staGledas.Service.Database.KlubFilmova", "Klub")
                        .WithMany("Objave")
                        .HasForeignKey("KlubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany("KlubObjave")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klub");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("staGledas.Service.Database.KorisniciUloge", b =>
                {
                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany("KorisniciUloge")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Uloge", "Uloga")
                        .WithMany("KorisniciUloge")
                        .HasForeignKey("UlogaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("staGledas.Service.Database.Novosti", b =>
                {
                    b.HasOne("staGledas.Service.Database.Korisnici", "Autor")
                        .WithMany("Novosti")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("staGledas.Service.Database.Poruke", b =>
                {
                    b.HasOne("staGledas.Service.Database.Korisnici", "Posiljatelj")
                        .WithMany("PoslanePoruke")
                        .HasForeignKey("PosiljateljId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Korisnici", "Primatelj")
                        .WithMany("PrimljenePoruke")
                        .HasForeignKey("PrimateljId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Posiljatelj");

                    b.Navigation("Primatelj");
                });

            modelBuilder.Entity("staGledas.Service.Database.Pratitelji", b =>
                {
                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany("Pratioci")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Korisnici", "Pratitelj")
                        .WithMany("Pratim")
                        .HasForeignKey("PratiteljId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Pratitelj");
                });

            modelBuilder.Entity("staGledas.Service.Database.Pretplate", b =>
                {
                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("staGledas.Service.Database.Recenzije", b =>
                {
                    b.HasOne("staGledas.Service.Database.Filmovi", "Film")
                        .WithMany("Recenzije")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany("Recenzije")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("staGledas.Service.Database.Watchlist", b =>
                {
                    b.HasOne("staGledas.Service.Database.Filmovi", "Film")
                        .WithMany("Watchlist")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany("Watchlist")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("staGledas.Service.Database.Zalbe", b =>
                {
                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Korisnici", "ObradioPrijavu")
                        .WithMany()
                        .HasForeignKey("ObradioPrijavuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("staGledas.Service.Database.Recenzije", "Recenzija")
                        .WithMany()
                        .HasForeignKey("RecenzijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("ObradioPrijavu");

                    b.Navigation("Recenzija");
                });

            modelBuilder.Entity("staGledas.Service.Database.Filmovi", b =>
                {
                    b.Navigation("Favoriti");

                    b.Navigation("FilmoviGlumci");

                    b.Navigation("FilmoviZanrovi");

                    b.Navigation("Lajkovi");

                    b.Navigation("Recenzije");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("staGledas.Service.Database.Glumci", b =>
                {
                    b.Navigation("FilmoviGlumci");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubFilmova", b =>
                {
                    b.Navigation("Clanovi");

                    b.Navigation("Objave");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubObjave", b =>
                {
                    b.Navigation("Komentari");

                    b.Navigation("Lajkovi");
                });

            modelBuilder.Entity("staGledas.Service.Database.Korisnici", b =>
                {
                    b.Navigation("Favoriti");

                    b.Navigation("FilmoviLajkovi");

                    b.Navigation("KlubKomentari");

                    b.Navigation("KlubLajkovi");

                    b.Navigation("KlubObjave");

                    b.Navigation("KorisniciUloge");

                    b.Navigation("Novosti");

                    b.Navigation("PoslanePoruke");

                    b.Navigation("Pratim");

                    b.Navigation("Pratioci");

                    b.Navigation("PrimljenePoruke");

                    b.Navigation("Recenzije");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("staGledas.Service.Database.Uloge", b =>
                {
                    b.Navigation("KorisniciUloge");
                });

            modelBuilder.Entity("staGledas.Service.Database.Zanrovi", b =>
                {
                    b.Navigation("FilmoviZanrovi");
                });
#pragma warning restore 612, 618
        }
    }
}
