// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using staGledas.Service.Database;

#nullable disable

namespace staGledas.Service.Migrations
{
    [DbContext(typeof(StaGledasContext))]
    partial class StaGledasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("staGledas.Service.Database.Favoriti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumDodavanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("KorisnikId", "FilmId")
                        .IsUnique();

                    b.ToTable("Favoriti");
                });

            modelBuilder.Entity("staGledas.Service.Database.Filmovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrojLajkova")
                        .HasColumnType("int");

                    b.Property<int?>("BrojOcjena")
                        .HasColumnType("int");

                    b.Property<int?>("BrojPregleda")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GodinaIzdanja")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ProsjecnaOcjena")
                        .HasColumnType("float");

                    b.Property<string>("Reziser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("int");

                    b.Property<int?>("Trajanje")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Naslov");

                    b.ToTable("Filmovi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrojOcjena = 3,
                            BrojPregleda = 500,
                            DatumIzmjene = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumKreiranja = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GodinaIzdanja = 2010,
                            Naslov = "Inception",
                            Opis = "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: inception.",
                            PosterPath = "/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg",
                            ProsjecnaOcjena = 4.2000000000000002,
                            Reziser = "Christopher Nolan",
                            TmdbId = 27205,
                            Trajanje = 148
                        },
                        new
                        {
                            Id = 2,
                            BrojOcjena = 2,
                            BrojPregleda = 450,
                            DatumIzmjene = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumKreiranja = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GodinaIzdanja = 1994,
                            Naslov = "The Shawshank Redemption",
                            Opis = "Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison.",
                            PosterPath = "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
                            ProsjecnaOcjena = 4.7000000000000002,
                            Reziser = "Frank Darabont",
                            TmdbId = 278,
                            Trajanje = 142
                        },
                        new
                        {
                            Id = 3,
                            BrojOcjena = 2,
                            BrojPregleda = 400,
                            DatumIzmjene = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumKreiranja = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GodinaIzdanja = 1972,
                            Naslov = "The Godfather",
                            Opis = "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family.",
                            PosterPath = "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
                            ProsjecnaOcjena = 4.4000000000000004,
                            Reziser = "Francis Ford Coppola",
                            TmdbId = 238,
                            Trajanje = 175
                        },
                        new
                        {
                            Id = 4,
                            BrojOcjena = 2,
                            BrojPregleda = 480,
                            DatumIzmjene = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumKreiranja = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GodinaIzdanja = 2008,
                            Naslov = "The Dark Knight",
                            Opis = "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations.",
                            PosterPath = "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
                            ProsjecnaOcjena = 4.2999999999999998,
                            Reziser = "Christopher Nolan",
                            TmdbId = 155,
                            Trajanje = 152
                        },
                        new
                        {
                            Id = 5,
                            BrojOcjena = 2,
                            BrojPregleda = 420,
                            DatumIzmjene = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumKreiranja = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GodinaIzdanja = 1994,
                            Naslov = "Pulp Fiction",
                            Opis = "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper.",
                            PosterPath = "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
                            ProsjecnaOcjena = 4.2999999999999998,
                            Reziser = "Quentin Tarantino",
                            TmdbId = 680,
                            Trajanje = 154
                        });
                });

            modelBuilder.Entity("staGledas.Service.Database.FilmoviLajkovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumLajka")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("KorisnikId", "FilmId")
                        .IsUnique();

                    b.ToTable("FilmoviLajkovi");
                });

            modelBuilder.Entity("staGledas.Service.Database.FilmoviZanrovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("ZanrId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("ZanrId");

                    b.ToTable("FilmoviZanrovi");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubFilmova", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxClanova")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("VlasnikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VlasnikId");

                    b.ToTable("KlubFilmova");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubFilmovaClanovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPridruzivanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("KlubId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Uloga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlubId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("KlubFilmovaClanovi");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubKomentari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("ObjavaId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentKomentarId")
                        .HasColumnType("int");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ObjavaId");

                    b.HasIndex("ParentKomentarId");

                    b.ToTable("KlubKomentari");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubLajkovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumLajka")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("ObjavaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjavaId");

                    b.HasIndex("KorisnikId", "ObjavaId")
                        .IsUnique();

                    b.ToTable("KlubLajkovi");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubObjave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumBrisanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KlubId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlubId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("KlubObjave");
                });

            modelBuilder.Entity("staGledas.Service.Database.Korisnici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumBrisanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LozinkaSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Ime");

                    b.HasIndex("Prezime");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumIzmjene = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumKreiranja = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@stagledas.com",
                            Ime = "Admin",
                            IsDeleted = false,
                            IsPremium = false,
                            KorisnickoIme = "admin",
                            LozinkaHash = "D2uLCiGXHRiNM+mNAr0cOchH+gQ=",
                            LozinkaSalt = "fStjlRc+0bKc+yId5mDA6Q==",
                            Prezime = "Admin",
                            Status = true,
                            Telefon = "061000000"
                        },
                        new
                        {
                            Id = 2,
                            DatumIzmjene = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DatumKreiranja = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test@stagledas.com",
                            Ime = "Test",
                            IsDeleted = false,
                            IsPremium = false,
                            KorisnickoIme = "test",
                            LozinkaHash = "D2uLCiGXHRiNM+mNAr0cOchH+gQ=",
                            LozinkaSalt = "fStjlRc+0bKc+yId5mDA6Q==",
                            Prezime = "User",
                            Status = true,
                            Telefon = "062000000"
                        });
                });

            modelBuilder.Entity("staGledas.Service.Database.KorisniciUloge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("UlogaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("UlogaId");

                    b.ToTable("KorisniciUloge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KorisnikId = 1,
                            UlogaId = 1
                        },
                        new
                        {
                            Id = 2,
                            KorisnikId = 2,
                            UlogaId = 2
                        },
                        new
                        {
                            Id = 3,
                            KorisnikId = 2,
                            UlogaId = 3
                        });
                });

            modelBuilder.Entity("staGledas.Service.Database.Novosti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<int?>("BrojPregleda")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naslov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Slika")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Novosti");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutorId = 1,
                            BrojPregleda = 1250,
                            DatumKreiranja = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naslov = "Oscari 2025: Kompletna lista nominacija",
                            Sadrzaj = "Akademija filmskih umjetnosti i nauka objavila je nominacije za 97. dodjelu Oscara. Anora predvodi sa 6 nominacija, a The Brutalist i Emilia Perez prate sa po 10 nominacija. Ceremonija dodjele održat će se 2. marta 2025. u Dolby Theatreu u Los Angelesu."
                        },
                        new
                        {
                            Id = 2,
                            AutorId = 1,
                            BrojPregleda = 890,
                            DatumKreiranja = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naslov = "Christopher Nolan najavio novi film za 2026.",
                            Sadrzaj = "Nakon uspjeha Oppenheimera, Christopher Nolan vraća se sa novim projektom. Film će biti snimljen u IMAX formatu i prema najavama radi se o originalnoj priči. Universal Pictures potvrdio je datum premijere za juli 2026. godine."
                        },
                        new
                        {
                            Id = 3,
                            AutorId = 1,
                            BrojPregleda = 567,
                            DatumKreiranja = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naslov = "Martin Scorsese priprema dokumentarac o klasičnom Hollywoodu",
                            Sadrzaj = "Legendarni reditelj Martin Scorsese najavio je novi dokumentarni film koji će istražiti zlatno doba Hollywooda 1940-ih i 1950-ih godina. Projekt će uključivati rijetke arhivske snimke i intervjue sa preživjelim legendama iz tog perioda."
                        },
                        new
                        {
                            Id = 4,
                            AutorId = 1,
                            BrojPregleda = 432,
                            DatumKreiranja = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naslov = "Streaming platforme dominiraju box office",
                            Sadrzaj = "Analiza filmske industrije pokazuje da streaming platforme nastavljaju transformirati način na koji gledamo filmove. Netflix, Amazon Prime i Apple TV+ ulažu rekordne budžete u originalne produkcije, dok tradicionalni studiji traže nove strategije za privlačenje publike u kina."
                        });
                });

            modelBuilder.Entity("staGledas.Service.Database.Obavijesti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumObrade")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KlubId")
                        .HasColumnType("int");

                    b.Property<string>("Poruka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PosiljateljId")
                        .HasColumnType("int");

                    b.Property<int>("PrimateljId")
                        .HasColumnType("int");

                    b.Property<bool>("Procitano")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KlubId");

                    b.HasIndex("PosiljateljId");

                    b.HasIndex("PrimateljId");

                    b.ToTable("Obavijesti");
                });

            modelBuilder.Entity("staGledas.Service.Database.Poruke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumCitanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumSlanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("PosiljateljId")
                        .HasColumnType("int");

                    b.Property<int>("PrimateljId")
                        .HasColumnType("int");

                    b.Property<bool>("Procitano")
                        .HasColumnType("bit");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PosiljateljId");

                    b.HasIndex("PrimateljId");

                    b.ToTable("Poruke");
                });

            modelBuilder.Entity("staGledas.Service.Database.Pratitelji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPracenja")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("PratiteljId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("PratiteljId");

                    b.ToTable("Pratitelji");
                });

            modelBuilder.Entity("staGledas.Service.Database.Pretplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumIsteka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumPocetka")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePriceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Pretplate");
                });

            modelBuilder.Entity("staGledas.Service.Database.Recenzije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumIzmjene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumSkrivanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<bool>("ImaSpoiler")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ocjena")
                        .HasColumnType("float");

                    b.Property<string>("Sadrzaj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Recenzije");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatumKreiranja = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 1,
                            ImaSpoiler = false,
                            IsHidden = false,
                            KorisnikId = 2,
                            Naslov = "Remek djelo modernog filma",
                            Ocjena = 5.0,
                            Sadrzaj = "Inception je vizualno zapanjujući film koji uspijeva kombinirati akciju sa dubokim filozofskim pitanjima o prirodi stvarnosti i snova. Nolan je stvorio jedinstveno filmsko iskustvo."
                        },
                        new
                        {
                            Id = 2,
                            DatumKreiranja = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 2,
                            ImaSpoiler = false,
                            IsHidden = false,
                            KorisnikId = 2,
                            Naslov = "Najbolji film svih vremena",
                            Ocjena = 5.0,
                            Sadrzaj = "The Shawshank Redemption je dirljiva priča o nadi i prijateljstvu. Tim Robbins i Morgan Freeman su nevjerovatni u svojim ulogama. Film koji vas nikad neće napustiti."
                        },
                        new
                        {
                            Id = 3,
                            DatumKreiranja = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 2,
                            ImaSpoiler = false,
                            IsHidden = false,
                            KorisnikId = 1,
                            Naslov = "Klasik koji se mora pogledati",
                            Ocjena = 4.5,
                            Sadrzaj = "Izvanredna adaptacija Stephen Kingove novele. Film koji demonstrira snagu ljudskog duha i važnost nade čak i u najtežim okolnostima."
                        },
                        new
                        {
                            Id = 4,
                            DatumKreiranja = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 3,
                            ImaSpoiler = false,
                            IsHidden = false,
                            KorisnikId = 2,
                            Naslov = "Epska saga o porodici i moći",
                            Ocjena = 4.5,
                            Sadrzaj = "Marlon Brando je nezaboravan kao Don Vito Corleone. Coppola je stvorio film koji definira žanr gangsterskih filmova. Svaka scena je savršeno režirana."
                        },
                        new
                        {
                            Id = 5,
                            DatumKreiranja = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 3,
                            ImaSpoiler = false,
                            IsHidden = false,
                            KorisnikId = 1,
                            Naslov = "Filmska historija",
                            Ocjena = 4.0,
                            Sadrzaj = "The Godfather je više od filma - to je kulturni fenomen koji je utjecao na generacije filmskih stvaralaca. Obavezno gledanje za svakog ljubitelja filma."
                        },
                        new
                        {
                            Id = 6,
                            DatumKreiranja = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 4,
                            ImaSpoiler = false,
                            IsHidden = false,
                            KorisnikId = 2,
                            Naslov = "Heath Ledger je genijalan",
                            Ocjena = 4.5,
                            Sadrzaj = "Ovaj film je dokaz da superherojski filmovi mogu biti ozbiljno umjetničko djelo. Heath Ledger kao Joker je jedna od najimpresivnijih transformacija u historiji filma."
                        },
                        new
                        {
                            Id = 7,
                            DatumKreiranja = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 4,
                            ImaSpoiler = false,
                            IsHidden = false,
                            KorisnikId = 1,
                            Naslov = "Najbolji Batman film",
                            Ocjena = 4.0,
                            Sadrzaj = "Nolan je transformirao Batman franšizu u nešto potpuno novo. Mračan, realističan i napeto režiran od početka do kraja."
                        },
                        new
                        {
                            Id = 8,
                            DatumKreiranja = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 5,
                            ImaSpoiler = false,
                            IsHidden = false,
                            KorisnikId = 2,
                            Naslov = "Tarantinov potpis",
                            Ocjena = 4.5,
                            Sadrzaj = "Pulp Fiction je revolucionirao nezavisni film 90-ih. Dijalozi su briljantni, struktura inovativna, a soundtrack savršen. Film koji zahtijeva višestruka gledanja."
                        },
                        new
                        {
                            Id = 9,
                            DatumKreiranja = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 5,
                            ImaSpoiler = false,
                            IsHidden = false,
                            KorisnikId = 1,
                            Naslov = "Kultni klasik",
                            Ocjena = 4.0,
                            Sadrzaj = "Nelinearna naracija i nezaboravni likovi čine ovaj film posebnim. Samuel L. Jackson i John Travolta su savršeni zajedno."
                        },
                        new
                        {
                            Id = 10,
                            DatumKreiranja = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 1,
                            ImaSpoiler = true,
                            IsHidden = false,
                            KorisnikId = 1,
                            Naslov = "Vizualno impresivan ali konfuzan",
                            Ocjena = 3.5,
                            Sadrzaj = "Film je tehnički briljantan ali ponekad previše kompliciran. Završetak ostavlja previše pitanja bez odgovora. Ipak, vrijedi pogledati bar jednom."
                        },
                        new
                        {
                            Id = 11,
                            DatumKreiranja = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 1,
                            ImaSpoiler = false,
                            IsHidden = false,
                            KorisnikId = 2,
                            Naslov = "Nolan nikad ne razočara",
                            Ocjena = 4.0,
                            Sadrzaj = "Još jedan dokaz Nolanovog genija. Kompleksna priča koja nagrađuje pažljive gledatelje. Hans Zimmerov soundtrack je fantastičan."
                        });
                });

            modelBuilder.Entity("staGledas.Service.Database.Uloge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uloge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naziv = "Administrator",
                            Opis = "Administrator sistema"
                        },
                        new
                        {
                            Id = 2,
                            Naziv = "Korisnik",
                            Opis = "Standardni korisnik"
                        },
                        new
                        {
                            Id = 3,
                            Naziv = "PremiumKorisnik",
                            Opis = "Premium korisnik sa dodatnim privilegijama"
                        });
                });

            modelBuilder.Entity("staGledas.Service.Database.Watchlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumDodavanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumGledanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<bool?>("Pogledano")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Watchlist");
                });

            modelBuilder.Entity("staGledas.Service.Database.Zalbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumObrade")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int?>("ObradioPrijavuId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Razlog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecenzijaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ObradioPrijavuId");

                    b.HasIndex("RecenzijaId");

                    b.ToTable("Zalbe");
                });

            modelBuilder.Entity("staGledas.Service.Database.Zanrovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zanrovi");
                });

            modelBuilder.Entity("staGledas.Service.Database.Favoriti", b =>
                {
                    b.HasOne("staGledas.Service.Database.Filmovi", "Film")
                        .WithMany("Favoriti")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany("Favoriti")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("staGledas.Service.Database.FilmoviLajkovi", b =>
                {
                    b.HasOne("staGledas.Service.Database.Filmovi", "Film")
                        .WithMany("Lajkovi")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany("FilmoviLajkovi")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("staGledas.Service.Database.FilmoviZanrovi", b =>
                {
                    b.HasOne("staGledas.Service.Database.Filmovi", "Film")
                        .WithMany("FilmoviZanrovi")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Zanrovi", "Zanr")
                        .WithMany("FilmoviZanrovi")
                        .HasForeignKey("ZanrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Zanr");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubFilmova", b =>
                {
                    b.HasOne("staGledas.Service.Database.Korisnici", "Vlasnik")
                        .WithMany()
                        .HasForeignKey("VlasnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vlasnik");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubFilmovaClanovi", b =>
                {
                    b.HasOne("staGledas.Service.Database.KlubFilmova", "Klub")
                        .WithMany("Clanovi")
                        .HasForeignKey("KlubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klub");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubKomentari", b =>
                {
                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany("KlubKomentari")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.KlubObjave", "Objava")
                        .WithMany("Komentari")
                        .HasForeignKey("ObjavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.KlubKomentari", "ParentKomentar")
                        .WithMany()
                        .HasForeignKey("ParentKomentarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Korisnik");

                    b.Navigation("Objava");

                    b.Navigation("ParentKomentar");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubLajkovi", b =>
                {
                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany("KlubLajkovi")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.KlubObjave", "Objava")
                        .WithMany("Lajkovi")
                        .HasForeignKey("ObjavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Objava");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubObjave", b =>
                {
                    b.HasOne("staGledas.Service.Database.KlubFilmova", "Klub")
                        .WithMany("Objave")
                        .HasForeignKey("KlubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany("KlubObjave")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klub");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("staGledas.Service.Database.KorisniciUloge", b =>
                {
                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany("KorisniciUloge")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Uloge", "Uloga")
                        .WithMany("KorisniciUloge")
                        .HasForeignKey("UlogaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("staGledas.Service.Database.Novosti", b =>
                {
                    b.HasOne("staGledas.Service.Database.Korisnici", "Autor")
                        .WithMany("Novosti")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("staGledas.Service.Database.Obavijesti", b =>
                {
                    b.HasOne("staGledas.Service.Database.KlubFilmova", "Klub")
                        .WithMany()
                        .HasForeignKey("KlubId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("staGledas.Service.Database.Korisnici", "Posiljatelj")
                        .WithMany()
                        .HasForeignKey("PosiljateljId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Korisnici", "Primatelj")
                        .WithMany()
                        .HasForeignKey("PrimateljId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klub");

                    b.Navigation("Posiljatelj");

                    b.Navigation("Primatelj");
                });

            modelBuilder.Entity("staGledas.Service.Database.Poruke", b =>
                {
                    b.HasOne("staGledas.Service.Database.Korisnici", "Posiljatelj")
                        .WithMany("PoslanePoruke")
                        .HasForeignKey("PosiljateljId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Korisnici", "Primatelj")
                        .WithMany("PrimljenePoruke")
                        .HasForeignKey("PrimateljId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Posiljatelj");

                    b.Navigation("Primatelj");
                });

            modelBuilder.Entity("staGledas.Service.Database.Pratitelji", b =>
                {
                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany("Pratioci")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Korisnici", "Pratitelj")
                        .WithMany("Pratim")
                        .HasForeignKey("PratiteljId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Pratitelj");
                });

            modelBuilder.Entity("staGledas.Service.Database.Pretplate", b =>
                {
                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("staGledas.Service.Database.Recenzije", b =>
                {
                    b.HasOne("staGledas.Service.Database.Filmovi", "Film")
                        .WithMany("Recenzije")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany("Recenzije")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("staGledas.Service.Database.Watchlist", b =>
                {
                    b.HasOne("staGledas.Service.Database.Filmovi", "Film")
                        .WithMany("Watchlist")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany("Watchlist")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("staGledas.Service.Database.Zalbe", b =>
                {
                    b.HasOne("staGledas.Service.Database.Korisnici", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("staGledas.Service.Database.Korisnici", "ObradioPrijavu")
                        .WithMany()
                        .HasForeignKey("ObradioPrijavuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("staGledas.Service.Database.Recenzije", "Recenzija")
                        .WithMany()
                        .HasForeignKey("RecenzijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("ObradioPrijavu");

                    b.Navigation("Recenzija");
                });

            modelBuilder.Entity("staGledas.Service.Database.Filmovi", b =>
                {
                    b.Navigation("Favoriti");

                    b.Navigation("FilmoviZanrovi");

                    b.Navigation("Lajkovi");

                    b.Navigation("Recenzije");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubFilmova", b =>
                {
                    b.Navigation("Clanovi");

                    b.Navigation("Objave");
                });

            modelBuilder.Entity("staGledas.Service.Database.KlubObjave", b =>
                {
                    b.Navigation("Komentari");

                    b.Navigation("Lajkovi");
                });

            modelBuilder.Entity("staGledas.Service.Database.Korisnici", b =>
                {
                    b.Navigation("Favoriti");

                    b.Navigation("FilmoviLajkovi");

                    b.Navigation("KlubKomentari");

                    b.Navigation("KlubLajkovi");

                    b.Navigation("KlubObjave");

                    b.Navigation("KorisniciUloge");

                    b.Navigation("Novosti");

                    b.Navigation("PoslanePoruke");

                    b.Navigation("Pratim");

                    b.Navigation("Pratioci");

                    b.Navigation("PrimljenePoruke");

                    b.Navigation("Recenzije");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("staGledas.Service.Database.Uloge", b =>
                {
                    b.Navigation("KorisniciUloge");
                });

            modelBuilder.Entity("staGledas.Service.Database.Zanrovi", b =>
                {
                    b.Navigation("FilmoviZanrovi");
                });
#pragma warning restore 612, 618
        }
    }
}
